
# Site settings
title: Cheng Wang
name: Cheng Wang
subtitle: Research Scientist
email: dr.rer.nat.chengwang@gmail.com
description: Home
baseurl: "https://deepsemantic.github.io."
url: "https://deepsemantic.github.io."
github_username:  deepsemantic
disqus_baseurl: "https://deepsemantic.github.io."
disqus_shortname: https-deepsemantic-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Cheng Wang"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: deepsemantic
    url: https://github.com/deepsemantic
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Cheng Wang
    url: https://www.linkedin.com/in/cheng-wang-88b08310b/
    desc: Connect with me on LinkedIn
    share: true
